# Generated by Django 5.0.7 on 2024-07-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertservice', '0004_alert_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='nickname',
        ),
    ]
