# Generated by Django 5.0.7 on 2024-07-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertservice', '0006_alter_alert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(default='Created', max_length=100),
        ),
    ]
