# Generated by Django 5.0.7 on 2024-07-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertservice', '0008_remove_alert_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='set_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
